.gitignore, build.sbt, project/build.properties, project/plugins.sbt, src/main/paradox/.htaccess, src/main/paradox/how-to-contribute.md, src/main/paradox/index.md, src/main/paradox/modules.md, src/main/paradox/what-is-pekko.md
Incorporates https://github.com/apache/incubator-pekko-site/pull/4
=> Add home page

.gitignore, build.sbt, project/build.properties, project/plugins.sbt, src/main/paradox/how-to-contribute.md, src/main/paradox/index.md, src/main/paradox/modules.md, src/main/paradox/what-is-pekko.md
Should we try to create the homepage with paradox as well? This is an early attempt to set it up.
=> simple paradox-based homepage setup

build.sbt
=> Use ApacheMavenSnapshotsRepo resolver constant

content/.htaccess, src/main/public/.htaccess
See https://github.com/apache/incubator-pekko/pull/461 for context
=> Add .htaccess rules for Pekko 1.0

content/.htaccess, src/main/public/.htaccess
* will need to see if it is possible to streamline all the 1.0.x redirects at bottom of file but will leave that to a separate PR
=> pekko 1.0.1 release

content/.htaccess, src/main/public/.htaccess
these 1.0.0 docs are not being published
=> connectors 1.0.0 docs

build.sbt, content/download.html, content/how-to-contribute.html, content/index.html, content/modules.html, content/what-is-pekko.html, project/plugins.sbt
* based on #35 
* uses snapshot release of sbt-paradox plugin - doing a new release is probably too much effort
=> Remove version

content/download.html, content/how-to-contribute.html, content/index.html, content/modules.html, content/what-is-pekko.html, project/build.properties, project/project-info.conf, src/main/paradox/download.md
also
* sbt 1.9.7
* fix broken link for sbt paradox download
* add project-info.conf to avoid warnings when building the docs
=> pekko projection release

content/assets/stylesheets/pekko-theme.css, content/download.html, content/how-to-contribute.html, content/index.html, content/modules.html, content/what-is-pekko.html, project/plugins.sbt
only affects the pages generated for the `.md` in this repo
=> uptake footer changes in paradox plugin

LICENSE, NOTICE
=> update license and notice

README.md
the line is not being emphasised - removing the spaces fixes that
=> fix emphasis in README.md

content/.htaccess, src/main/public/.htaccess
I've tried these out on https://pekko.staged.apache.org
these changes get us an A grade on https://securityheaders.com
eg https://securityheaders.com/?q=https%3A%2F%2Fpekko.staged.apache.org%2F&hide=on&followRedirects=on
=> add security headers

LICENSE, content/assets/javascripts/paradox-material-theme.js, src/main/paradox/_template/assets/javascripts/paradox-material-theme.js
=> update license links

content/index.html, content/samples.html, src/main/paradox/index.md, src/main/paradox/samples.md
=> fix link of pekko-sample-distributed-workers-scala

.github/workflows/site.yml, content/download.html, content/how-to-contribute.html, content/index.html, content/modules.html, content/samples.html, project/plugins.sbt
latest plugin prefers Java 8 - https://github.com/apache/incubator-pekko-sbt-paradox
=> uptake latest paradox plugin

content/.htaccess, src/main/public/.htaccess
pekko core now has 1.1.0-M1 release
=> redirect 1.1 docs

content/.htaccess, src/main/public/.htaccess
needed for link validator in https://github.com/apache/pekko-http/pull/560
=> add redirects for milestones

content/.htaccess, src/main/public/.htaccess
* add a few versions so that we don't have to add new entries with every single release
* also moves the 1.0 and 1.1 redirects above the x.y.z redirects
=> add some version redirects

content/.htaccess, src/main/public/.htaccess
see https://github.com/apache/pekko-http/pull/604#issuecomment-2352735949
=> redirect broken migration doc link

content/.htaccess, src/main/public/.htaccess
part of pekko-management release
=> redirect management/current to 1.1

NOTICE, project/build.properties
=> upgrade sbt

content/.htaccess, src/main/public/.htaccess
=> redirect projection/current to 1.1
